global:
  name: React Landscape
  short_name: React
  repo: openjs-operations/react-landscape
  website: https://react-landscape.openjsf.org
  short_domain: react-landscape.openjsf.org
  company_url: https://reactjs.org
  email: info@reactjs.org
  self: https://www.crunchbase.com/organization/open-js-foundation
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  meta:
    title: React Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@reactjs'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: React Members
  skip_funding: true
  flags:
    hide_license_for_categories:
      - GraphQL Adopter
      - React Members
twitter:
  search: react-landscape.openjsf.org
  url: https://react-landscape.openjsf.org
  text: React Landscape
relation:
  label: GraphQL Relation
  url: reactjs
  values:
    - id: hosted
      label: React Projects
      children:
        - id: foundationproject
          label: React Project
          prefix: React
          tag: React Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: React Project
          big_picture_color: rgb(24,54,114)
    - id: company
      label: React Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: React Member Products/Projects
      tag: React Members
    - id: false
      label: Non-React Member Products/Projects
      url: 'no'
membership:
  General:
    name: GraphQL
    label: Member
    funding: General
  'false':
    funding: 'No'
home:
  header: >
    <h1>React Landscape</h1> The React landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://openjsf.org/join
    image: /images/support-react.svg
    title: Become a member!
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: React Landscape
    fullscreen_header: See the interactive landscape at react-landscape.openjsf.org
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 475
        height: 160
        top: 0
        left: 0
        color: rgb(7,136,62)
        fit_width: true
      - type: HorizontalCategory
        category: React Members
        rows: 3
        width: 455
        height: 160
        top: 0
        left: 495
        color: rgb(79,121,13)
        fit_width: true
      - type: HorizontalCategory
        category: Technical leadership
        rows: 6
        width: 970
        height: 195
        top: 180
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: Adopters
        rows: 4
        width: 650
        height: 150
        top: 390
        left: 0
        color: rgb(103,66,18)
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 150
        top: 390
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the React community and its financial and technical leadership.
            top: 45
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: react-landscape.openjsf.org
            top: 95
            left: 10
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 90
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 90
            right: 10
            top: 10
            title: React Logo
test:
  header: React Landscape
  section: React Project
  logo: componentkit.svg
